server:
  port: 9000  # 9000번 포트로 실행

#spring:
#  application:
#    name: demo
#
#  datasource:
#    platform: mysql
#    url: jdbc:mysql://molly-db.cbqsk77rslwx.ap-northeast-2.rds.amazonaws.com/board
#    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
#    username: master # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
#    password: kim7131927! # 비밀번호를 입력해주세요!
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
#    platform: mysql
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: root # 만약 따로 설정하지 않으셨다면 기본값은 admin 입니다
    password: kim7131927! # 비밀번호를 입력해주세요!
    driver-class-name: com.mysql.cj.jdbc.Driver


